{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: api
  {{- if and .Values.ingress.enabled .Values.api.backendConfig.enabled }}
  annotations:
    cloud.google.com/backend-config: '{"ports": {"http":"{{ .Values.api.backendConfig.name }}"}}'
  {{- end }}
spec:
  type: {{ .Values.api.service.type }}
  selector:
    app.kubernetes.io/name: api
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.port }}
{{- end }}
---
{{- if and .Values.api.enabled .Values.api.internalService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: api-internal
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: api
  ports:
    - name: http-internal
      port: {{ .Values.api.internalService.port }}
      targetPort: {{ .Values.api.internalService.port }}
{{- end }}
