{{- if .Values.api.enabled }}
{{- $apiTag := default .Values.global.images.tag .Values.api.image.tag }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api
    spec:
      containers:
        - name: api
          image: "{{ .Values.global.images.registryHost }}/{{ .Values.global.images.projectId }}/{{ .Values.global.images.repository }}/{{ .Values.api.image.name }}:{{ $apiTag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
{{- if or .Values.api.env .Values.api.secretEnv }}
          env:
{{- range $name, $value := .Values.api.env }}
            - name: {{ $name }}
              value: {{ $value | quote }}
{{- end }}
{{- range $name, $ref := .Values.api.secretEnv }}
            - name: {{ $name }}
              valueFrom:
                secretKeyRef:
                  name: {{ $ref.secretName | quote }}
                  key: {{ $ref.secretKey | quote }}
{{- end }}
{{- end }}
          ports:
            - containerPort: {{ .Values.api.service.port }}
{{- end }}
