{{- if and .Values.openclaw.enabled .Values.openclaw.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.openclaw.serviceAccount.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: openclaw
{{- if .Values.openclaw.serviceAccount.gcpServiceAccountEmail }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.openclaw.serviceAccount.gcpServiceAccountEmail | quote }}
{{- end }}
{{- end }}
