{{- if .Values.providerGateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: provider-gateway-headless
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: provider-gateway
spec:
  clusterIP: None
  publishNotReadyAddresses: false
  selector:
    app.kubernetes.io/name: provider-gateway
  ports:
    - name: http
      port: {{ .Values.providerGateway.service.port }}
      targetPort: {{ .Values.providerGateway.service.port }}
{{- end }}
