{{- if and .Values.runtime.enabled .Values.runtime.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.runtime.serviceAccount.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: runtime
{{- if .Values.runtime.serviceAccount.gcpServiceAccountEmail }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.runtime.serviceAccount.gcpServiceAccountEmail | quote }}
{{- end }}
{{- end }}
