{{- if and .Values.sandbox.enabled .Values.sandbox.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.sandbox.serviceAccount.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: sandbox
{{- if .Values.sandbox.serviceAccount.gcpServiceAccountEmail }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.sandbox.serviceAccount.gcpServiceAccountEmail | quote }}
{{- end }}
{{- end }}
