{{- if .Values.web.enabled }}
{{- $webTag := default .Values.global.images.tag .Values.web.image.tag }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: web
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web
    spec:
      containers:
        - name: web
          image: "{{ .Values.global.images.registryHost }}/{{ .Values.global.images.projectId }}/{{ .Values.global.images.repository }}/{{ .Values.web.image.name }}:{{ $webTag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.web.service.port }}
{{- end }}
