{{- if and .Values.api.enabled .Values.api.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: api
spec:
  minAvailable: {{ .Values.api.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: api
---
{{- end }}
{{- if and .Values.web.enabled .Values.web.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: web
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: web
spec:
  minAvailable: {{ .Values.web.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: web
---
{{- end }}
{{- if and .Values.providerGateway.enabled .Values.providerGateway.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: provider-gateway
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: provider-gateway
spec:
  minAvailable: {{ .Values.providerGateway.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: provider-gateway
---
{{- end }}
{{- if and .Values.runtime.enabled .Values.runtime.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: runtime
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: runtime
spec:
  minAvailable: {{ .Values.runtime.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: runtime
---
{{- end }}
