steps:
  - name: gcr.io/cloud-builders/docker
    env:
      - DOCKER_BUILDKIT=1
    args:
      - build
      - -f
      - Dockerfile.sandbox
      - -t
      - ${_SANDBOX_IMAGE}
      - .
  - name: gcr.io/cloud-builders/docker
    env:
      - DOCKER_BUILDKIT=1
    args:
      - build
      - -f
      - Dockerfile.sandbox-common
      - --build-arg
      - BASE_IMAGE=${_SANDBOX_IMAGE}
      - -t
      - ${_SANDBOX_COMMON_IMAGE}
      - .
images:
  - ${_SANDBOX_IMAGE}
  - ${_SANDBOX_COMMON_IMAGE}
