global:
  namespace: persai-dev
  images:
    registryHost: europe-west1-docker.pkg.dev
    projectId: project-44786b14-b7d7-4554-a8a
    repository: persai
    tag: d1c6590abf4d61adbbb2bae259bc88d80feacdfd

api:
  enabled: true
  replicaCount: 1
  image:
    name: api
    tag: d1c6590abf4d61adbbb2bae259bc88d80feacdfd
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3001

web:
  enabled: true
  replicaCount: 1
  image:
    name: web
    tag: d1c6590abf4d61adbbb2bae259bc88d80feacdfd
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3000

openclaw:
  enabled: false
  replicaCount: 1
  image:
    name: openclaw
    tag: d1c6590abf4d61adbbb2bae259bc88d80feacdfd
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
