import { runRuntimeConfigTest } from "./runtime-config.test";
import { runRuntimeBundleCoordinatorServiceTest } from "./runtime-bundle-coordinator.service.test";
import { runRuntimeBundleRegistryServiceTest } from "./runtime-bundle-registry.service.test";
import { runRuntimeBundleAutoRefreshServiceTest } from "./runtime-bundle-auto-refresh.service.test";
import { runRuntimeStateKeyspaceServiceTest } from "./runtime-state-keyspace.service.test";
import { runRuntimeStatePostgresServiceTest } from "./runtime-state-postgres.service.test";
import { runRuntimeStateRedisServiceTest } from "./runtime-state-redis.service.test";
import { runProviderGatewayClientServiceTest } from "./provider-gateway.client.service.test";
import { runSessionLeaseServiceTest } from "./session-lease.service.test";
import { runSessionCompactionServiceTest } from "./session-compaction.service.test";
import { runSessionStoreServiceTest } from "./session-store.service.test";
import { runIdempotencyServiceTest } from "./idempotency.service.test";
import { runTurnAcceptanceServiceTest } from "./turn-acceptance.service.test";
import { runPromptCacheStableBlocksTest } from "./prompt-cache-stable-blocks.test";
import { runPromptCacheStablePrefixGuardTest } from "./prompt-cache-stable-prefix-guard.test";
import { runCrossSessionCarryOverRendererTest } from "./cross-session-carry-over-renderer.test";
import { runPresenceRendererTest } from "./presence-renderer.test";
import { runRelativeTimeFormatterTest } from "./relative-time-formatter.test";
import { runTurnContextHydrationServiceTest } from "./turn-context-hydration.service.test";
import { runTurnExecutionServiceTest, runRecentPdfsHintTests } from "./turn-execution.service.test";
import { runTurnFinalizationServiceTest } from "./turn-finalization.service.test";
import { runTurnLeaseHeartbeatServiceTest } from "./turn-lease-heartbeat.service.test";
import { runInternalRuntimeDocumentJobsControllerTest } from "./internal-runtime-document-jobs.controller.test";
import { runRuntimeMediaTranscriptionServiceTest } from "./runtime-media-transcription.service.test";
import {
  runRuntimeBackgroundTaskEvaluationServiceTest,
  runQuotaAdvisoryClassificationTest
} from "./runtime-background-task-evaluation.service.test";
import { runRuntimeQuotaStatusToolServiceTest } from "./runtime-quota-status-tool.service.test";
import { runRuntimeScheduledActionToolServiceTest } from "./runtime-scheduled-action-tool.service.test";
import { runRuntimeTtsToolServiceTest } from "./runtime-tts-tool.service.test";
import { runRuntimeBrowserToolServiceTest } from "./runtime-browser-tool.service.test";
import { runRuntimeVideoGenerateToolServiceTest } from "./runtime-video-generate-tool.service.test";
import { runRuntimeMemoryWriteToolServiceTest } from "./runtime-memory-write-tool.service.test";
import { runSanitizeToolResultForModelTest } from "./sanitize-tool-result-for-model.test";
import { runToolBudgetPolicyTest } from "./tool-budget-policy.test";
import { runAssembleWorkingNotesAndAnswerTest } from "./assemble-working-notes-and-answer.test";
import { runBuildSystemReminderBlocksServiceTest } from "./build-system-reminder-blocks.service.test";
import { runAdr119GoldenPromptSnapshotTest } from "./adr119-golden-prompt-snapshot.test";
import { runAdr119Invariantstest } from "./native-tool-projection.test";
import { runModelOutputBudgetTest } from "./model-output-budget.test";
import { runRuntimeTextOnlyMultimodalSanitizerTest } from "./runtime-text-only-multimodal-sanitizer.test";

async function run(): Promise<void> {
  await runRuntimeConfigTest();
  await runRuntimeBundleCoordinatorServiceTest();
  await runRuntimeBundleRegistryServiceTest();
  await runRuntimeBundleAutoRefreshServiceTest();
  await runRuntimeStateKeyspaceServiceTest();
  await runRuntimeStatePostgresServiceTest();
  await runRuntimeStateRedisServiceTest();
  await runProviderGatewayClientServiceTest();
  await runRuntimeMediaTranscriptionServiceTest();
  await runRuntimeBackgroundTaskEvaluationServiceTest();
  await runQuotaAdvisoryClassificationTest();
  await runRuntimeQuotaStatusToolServiceTest();
  await runRuntimeScheduledActionToolServiceTest();
  await runRuntimeTtsToolServiceTest();
  await runRuntimeBrowserToolServiceTest();
  await runRuntimeVideoGenerateToolServiceTest();
  await runRuntimeMemoryWriteToolServiceTest();
  await runSessionStoreServiceTest();
  await runSessionLeaseServiceTest();
  await runSessionCompactionServiceTest();
  await runIdempotencyServiceTest();
  await runTurnAcceptanceServiceTest();
  await runPromptCacheStableBlocksTest();
  await runPromptCacheStablePrefixGuardTest();
  await runCrossSessionCarryOverRendererTest();
  await runRelativeTimeFormatterTest();
  await runPresenceRendererTest();
  await runTurnContextHydrationServiceTest();
  await runToolBudgetPolicyTest();
  await runAssembleWorkingNotesAndAnswerTest();
  await runSanitizeToolResultForModelTest();
  await runBuildSystemReminderBlocksServiceTest();
  await runTurnExecutionServiceTest();
  await runRecentPdfsHintTests();
  await runTurnFinalizationServiceTest();
  await runTurnLeaseHeartbeatServiceTest();
  await runInternalRuntimeDocumentJobsControllerTest();
  const { runTurnRoutingServiceTest } = await import("./turn-routing.service.test");
  await runTurnRoutingServiceTest();
  await runAdr119GoldenPromptSnapshotTest();
  await runAdr119Invariantstest();
  await runModelOutputBudgetTest();
  await runRuntimeTextOnlyMultimodalSanitizerTest();
}

run().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
